// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tag/collection.proto

package tag

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 添加标签的请求
type CollectionAddTagRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flag                 int64    `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Alias                string   `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionAddTagRequest) Reset()         { *m = CollectionAddTagRequest{} }
func (m *CollectionAddTagRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionAddTagRequest) ProtoMessage()    {}
func (*CollectionAddTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{0}
}

func (m *CollectionAddTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionAddTagRequest.Unmarshal(m, b)
}
func (m *CollectionAddTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionAddTagRequest.Marshal(b, m, deterministic)
}
func (m *CollectionAddTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionAddTagRequest.Merge(m, src)
}
func (m *CollectionAddTagRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionAddTagRequest.Size(m)
}
func (m *CollectionAddTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionAddTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionAddTagRequest proto.InternalMessageInfo

func (m *CollectionAddTagRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CollectionAddTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollectionAddTagRequest) GetFlag() int64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *CollectionAddTagRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

// 删除标签的请求
type CollectionRemoveTagRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionRemoveTagRequest) Reset()         { *m = CollectionRemoveTagRequest{} }
func (m *CollectionRemoveTagRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionRemoveTagRequest) ProtoMessage()    {}
func (*CollectionRemoveTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{1}
}

func (m *CollectionRemoveTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionRemoveTagRequest.Unmarshal(m, b)
}
func (m *CollectionRemoveTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionRemoveTagRequest.Marshal(b, m, deterministic)
}
func (m *CollectionRemoveTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionRemoveTagRequest.Merge(m, src)
}
func (m *CollectionRemoveTagRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionRemoveTagRequest.Size(m)
}
func (m *CollectionRemoveTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionRemoveTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionRemoveTagRequest proto.InternalMessageInfo

func (m *CollectionRemoveTagRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// 更新标签的请求
type CollectionUpdateTagRequest struct {
	Code                 string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flag                 int64             `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Alias                map[string]string `protobuf:"bytes,4,rep,name=alias,proto3" json:"alias,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Keyword              []string          `protobuf:"bytes,5,rep,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CollectionUpdateTagRequest) Reset()         { *m = CollectionUpdateTagRequest{} }
func (m *CollectionUpdateTagRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionUpdateTagRequest) ProtoMessage()    {}
func (*CollectionUpdateTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{2}
}

func (m *CollectionUpdateTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionUpdateTagRequest.Unmarshal(m, b)
}
func (m *CollectionUpdateTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionUpdateTagRequest.Marshal(b, m, deterministic)
}
func (m *CollectionUpdateTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionUpdateTagRequest.Merge(m, src)
}
func (m *CollectionUpdateTagRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionUpdateTagRequest.Size(m)
}
func (m *CollectionUpdateTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionUpdateTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionUpdateTagRequest proto.InternalMessageInfo

func (m *CollectionUpdateTagRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CollectionUpdateTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollectionUpdateTagRequest) GetFlag() int64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *CollectionUpdateTagRequest) GetAlias() map[string]string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *CollectionUpdateTagRequest) GetKeyword() []string {
	if m != nil {
		return m.Keyword
	}
	return nil
}

// 列举标签的请求
type CollectionListTagRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionListTagRequest) Reset()         { *m = CollectionListTagRequest{} }
func (m *CollectionListTagRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionListTagRequest) ProtoMessage()    {}
func (*CollectionListTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{3}
}

func (m *CollectionListTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionListTagRequest.Unmarshal(m, b)
}
func (m *CollectionListTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionListTagRequest.Marshal(b, m, deterministic)
}
func (m *CollectionListTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionListTagRequest.Merge(m, src)
}
func (m *CollectionListTagRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionListTagRequest.Size(m)
}
func (m *CollectionListTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionListTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionListTagRequest proto.InternalMessageInfo

func (m *CollectionListTagRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *CollectionListTagRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 列举标签的回复
type CollectionListTagResponse struct {
	Status               *Status      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Tag                  []*TagEntity `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CollectionListTagResponse) Reset()         { *m = CollectionListTagResponse{} }
func (m *CollectionListTagResponse) String() string { return proto.CompactTextString(m) }
func (*CollectionListTagResponse) ProtoMessage()    {}
func (*CollectionListTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{4}
}

func (m *CollectionListTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionListTagResponse.Unmarshal(m, b)
}
func (m *CollectionListTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionListTagResponse.Marshal(b, m, deterministic)
}
func (m *CollectionListTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionListTagResponse.Merge(m, src)
}
func (m *CollectionListTagResponse) XXX_Size() int {
	return xxx_messageInfo_CollectionListTagResponse.Size(m)
}
func (m *CollectionListTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionListTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionListTagResponse proto.InternalMessageInfo

func (m *CollectionListTagResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CollectionListTagResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CollectionListTagResponse) GetTag() []*TagEntity {
	if m != nil {
		return m.Tag
	}
	return nil
}

// 搜索标签的请求
type CollectionSearchTagRequest struct {
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionSearchTagRequest) Reset()         { *m = CollectionSearchTagRequest{} }
func (m *CollectionSearchTagRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionSearchTagRequest) ProtoMessage()    {}
func (*CollectionSearchTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{5}
}

func (m *CollectionSearchTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionSearchTagRequest.Unmarshal(m, b)
}
func (m *CollectionSearchTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionSearchTagRequest.Marshal(b, m, deterministic)
}
func (m *CollectionSearchTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionSearchTagRequest.Merge(m, src)
}
func (m *CollectionSearchTagRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionSearchTagRequest.Size(m)
}
func (m *CollectionSearchTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionSearchTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionSearchTagRequest proto.InternalMessageInfo

func (m *CollectionSearchTagRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *CollectionSearchTagRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *CollectionSearchTagRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 搜索标签的回复
type CollectionSearchTagResponse struct {
	Status               *Status      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Tag                  []*TagEntity `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CollectionSearchTagResponse) Reset()         { *m = CollectionSearchTagResponse{} }
func (m *CollectionSearchTagResponse) String() string { return proto.CompactTextString(m) }
func (*CollectionSearchTagResponse) ProtoMessage()    {}
func (*CollectionSearchTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{6}
}

func (m *CollectionSearchTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionSearchTagResponse.Unmarshal(m, b)
}
func (m *CollectionSearchTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionSearchTagResponse.Marshal(b, m, deterministic)
}
func (m *CollectionSearchTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionSearchTagResponse.Merge(m, src)
}
func (m *CollectionSearchTagResponse) XXX_Size() int {
	return xxx_messageInfo_CollectionSearchTagResponse.Size(m)
}
func (m *CollectionSearchTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionSearchTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionSearchTagResponse proto.InternalMessageInfo

func (m *CollectionSearchTagResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CollectionSearchTagResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CollectionSearchTagResponse) GetTag() []*TagEntity {
	if m != nil {
		return m.Tag
	}
	return nil
}

// 智能提示关键字的请求
type CollectionSuggestFilterRequest struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionSuggestFilterRequest) Reset()         { *m = CollectionSuggestFilterRequest{} }
func (m *CollectionSuggestFilterRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionSuggestFilterRequest) ProtoMessage()    {}
func (*CollectionSuggestFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{7}
}

func (m *CollectionSuggestFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionSuggestFilterRequest.Unmarshal(m, b)
}
func (m *CollectionSuggestFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionSuggestFilterRequest.Marshal(b, m, deterministic)
}
func (m *CollectionSuggestFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionSuggestFilterRequest.Merge(m, src)
}
func (m *CollectionSuggestFilterRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionSuggestFilterRequest.Size(m)
}
func (m *CollectionSuggestFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionSuggestFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionSuggestFilterRequest proto.InternalMessageInfo

func (m *CollectionSuggestFilterRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

// 智能提示过滤器的回复
type CollectionSuggestFilterResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Filter               []string `protobuf:"bytes,2,rep,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionSuggestFilterResponse) Reset()         { *m = CollectionSuggestFilterResponse{} }
func (m *CollectionSuggestFilterResponse) String() string { return proto.CompactTextString(m) }
func (*CollectionSuggestFilterResponse) ProtoMessage()    {}
func (*CollectionSuggestFilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{8}
}

func (m *CollectionSuggestFilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionSuggestFilterResponse.Unmarshal(m, b)
}
func (m *CollectionSuggestFilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionSuggestFilterResponse.Marshal(b, m, deterministic)
}
func (m *CollectionSuggestFilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionSuggestFilterResponse.Merge(m, src)
}
func (m *CollectionSuggestFilterResponse) XXX_Size() int {
	return xxx_messageInfo_CollectionSuggestFilterResponse.Size(m)
}
func (m *CollectionSuggestFilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionSuggestFilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionSuggestFilterResponse proto.InternalMessageInfo

func (m *CollectionSuggestFilterResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CollectionSuggestFilterResponse) GetFilter() []string {
	if m != nil {
		return m.Filter
	}
	return nil
}

// 替换关键字的请求
type CollectionReplaceKeywordRequest struct {
	MatchedValue         string   `protobuf:"bytes,1,opt,name=matchedValue,proto3" json:"matchedValue,omitempty"`
	NewValue             string   `protobuf:"bytes,2,opt,name=newValue,proto3" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionReplaceKeywordRequest) Reset()         { *m = CollectionReplaceKeywordRequest{} }
func (m *CollectionReplaceKeywordRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionReplaceKeywordRequest) ProtoMessage()    {}
func (*CollectionReplaceKeywordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{9}
}

func (m *CollectionReplaceKeywordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionReplaceKeywordRequest.Unmarshal(m, b)
}
func (m *CollectionReplaceKeywordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionReplaceKeywordRequest.Marshal(b, m, deterministic)
}
func (m *CollectionReplaceKeywordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionReplaceKeywordRequest.Merge(m, src)
}
func (m *CollectionReplaceKeywordRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionReplaceKeywordRequest.Size(m)
}
func (m *CollectionReplaceKeywordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionReplaceKeywordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionReplaceKeywordRequest proto.InternalMessageInfo

func (m *CollectionReplaceKeywordRequest) GetMatchedValue() string {
	if m != nil {
		return m.MatchedValue
	}
	return ""
}

func (m *CollectionReplaceKeywordRequest) GetNewValue() string {
	if m != nil {
		return m.NewValue
	}
	return ""
}

// 扩展关键字的请求
type CollectionExtendKeywordRequest struct {
	Mode                 ExtendMode `protobuf:"varint,1,opt,name=mode,proto3,enum=tag.ExtendMode" json:"mode,omitempty"`
	MatchedValue         []string   `protobuf:"bytes,2,rep,name=matchedValue,proto3" json:"matchedValue,omitempty"`
	NewValue             []string   `protobuf:"bytes,3,rep,name=newValue,proto3" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CollectionExtendKeywordRequest) Reset()         { *m = CollectionExtendKeywordRequest{} }
func (m *CollectionExtendKeywordRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionExtendKeywordRequest) ProtoMessage()    {}
func (*CollectionExtendKeywordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{10}
}

func (m *CollectionExtendKeywordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionExtendKeywordRequest.Unmarshal(m, b)
}
func (m *CollectionExtendKeywordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionExtendKeywordRequest.Marshal(b, m, deterministic)
}
func (m *CollectionExtendKeywordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionExtendKeywordRequest.Merge(m, src)
}
func (m *CollectionExtendKeywordRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionExtendKeywordRequest.Size(m)
}
func (m *CollectionExtendKeywordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionExtendKeywordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionExtendKeywordRequest proto.InternalMessageInfo

func (m *CollectionExtendKeywordRequest) GetMode() ExtendMode {
	if m != nil {
		return m.Mode
	}
	return ExtendMode_INVALID
}

func (m *CollectionExtendKeywordRequest) GetMatchedValue() []string {
	if m != nil {
		return m.MatchedValue
	}
	return nil
}

func (m *CollectionExtendKeywordRequest) GetNewValue() []string {
	if m != nil {
		return m.NewValue
	}
	return nil
}

// 合并Json格式数据的请求
type CollectionMergeJsonRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionMergeJsonRequest) Reset()         { *m = CollectionMergeJsonRequest{} }
func (m *CollectionMergeJsonRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionMergeJsonRequest) ProtoMessage()    {}
func (*CollectionMergeJsonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{11}
}

func (m *CollectionMergeJsonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionMergeJsonRequest.Unmarshal(m, b)
}
func (m *CollectionMergeJsonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionMergeJsonRequest.Marshal(b, m, deterministic)
}
func (m *CollectionMergeJsonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionMergeJsonRequest.Merge(m, src)
}
func (m *CollectionMergeJsonRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionMergeJsonRequest.Size(m)
}
func (m *CollectionMergeJsonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionMergeJsonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionMergeJsonRequest proto.InternalMessageInfo

func (m *CollectionMergeJsonRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*CollectionAddTagRequest)(nil), "tag.CollectionAddTagRequest")
	proto.RegisterType((*CollectionRemoveTagRequest)(nil), "tag.CollectionRemoveTagRequest")
	proto.RegisterType((*CollectionUpdateTagRequest)(nil), "tag.CollectionUpdateTagRequest")
	proto.RegisterMapType((map[string]string)(nil), "tag.CollectionUpdateTagRequest.AliasEntry")
	proto.RegisterType((*CollectionListTagRequest)(nil), "tag.CollectionListTagRequest")
	proto.RegisterType((*CollectionListTagResponse)(nil), "tag.CollectionListTagResponse")
	proto.RegisterType((*CollectionSearchTagRequest)(nil), "tag.CollectionSearchTagRequest")
	proto.RegisterType((*CollectionSearchTagResponse)(nil), "tag.CollectionSearchTagResponse")
	proto.RegisterType((*CollectionSuggestFilterRequest)(nil), "tag.CollectionSuggestFilterRequest")
	proto.RegisterType((*CollectionSuggestFilterResponse)(nil), "tag.CollectionSuggestFilterResponse")
	proto.RegisterType((*CollectionReplaceKeywordRequest)(nil), "tag.CollectionReplaceKeywordRequest")
	proto.RegisterType((*CollectionExtendKeywordRequest)(nil), "tag.CollectionExtendKeywordRequest")
	proto.RegisterType((*CollectionMergeJsonRequest)(nil), "tag.CollectionMergeJsonRequest")
}

func init() {
	proto.RegisterFile("proto/tag/collection.proto", fileDescriptor_b2a89965900be93e)
}

var fileDescriptor_b2a89965900be93e = []byte{
	// 671 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x12, 0x37, 0xe9, 0x97, 0x29, 0x2d, 0x68, 0x55, 0x15, 0x63, 0xa0, 0x8d, 0xdc, 0x5e,
	0x44, 0x5c, 0xa4, 0x28, 0x48, 0x55, 0x85, 0xb8, 0xa0, 0x45, 0x45, 0xa8, 0xb4, 0x12, 0x72, 0x4b,
	0xaf, 0x10, 0xd2, 0xd6, 0x9e, 0x38, 0x51, 0x9c, 0xdd, 0x60, 0xaf, 0xdb, 0x86, 0x7b, 0xde, 0x86,
	0x67, 0xe3, 0x19, 0x90, 0x77, 0xfd, 0xff, 0x53, 0x09, 0x09, 0x71, 0xe7, 0xd9, 0x99, 0x3d, 0x7b,
	0xce, 0xee, 0x99, 0x31, 0x18, 0x0b, 0x9f, 0x0b, 0xbe, 0x2f, 0xa8, 0xbb, 0x6f, 0x73, 0xcf, 0x43,
	0x5b, 0x4c, 0x39, 0x1b, 0xca, 0x45, 0xa2, 0x09, 0xea, 0x1a, 0x5b, 0x59, 0x41, 0x30, 0xa1, 0x3e,
	0x3a, 0x2a, 0x69, 0xce, 0xe0, 0xf1, 0xbb, 0x74, 0xc3, 0x91, 0xe3, 0x5c, 0x52, 0xd7, 0xc2, 0x6f,
	0x21, 0x06, 0x82, 0x10, 0x58, 0xb1, 0xb9, 0x83, 0x7a, 0xab, 0xdf, 0x1a, 0xf4, 0x2c, 0xf9, 0x1d,
	0xad, 0x31, 0x3a, 0x47, 0xbd, 0xad, 0xd6, 0xa2, 0xef, 0x68, 0x6d, 0xec, 0x51, 0x57, 0xd7, 0xfa,
	0xad, 0x81, 0x66, 0xc9, 0x6f, 0xb2, 0x09, 0x1d, 0xea, 0x4d, 0x69, 0xa0, 0xaf, 0xc8, 0x42, 0x15,
	0x98, 0x2f, 0xc1, 0xc8, 0x0e, 0xb3, 0x70, 0xce, 0x6f, 0xf0, 0xfe, 0xf3, 0xcc, 0x5f, 0xad, 0xfc,
	0x96, 0xcf, 0x0b, 0x87, 0x0a, 0xfc, 0x4b, 0x14, 0xdf, 0x66, 0x14, 0xb5, 0xc1, 0xda, 0xe8, 0xc5,
	0x50, 0x50, 0x77, 0xd8, 0x7c, 0xd6, 0xf0, 0x28, 0x2a, 0x3e, 0x61, 0xc2, 0x5f, 0xc6, 0x72, 0x88,
	0x0e, 0xab, 0x33, 0x5c, 0xde, 0x72, 0xdf, 0xd1, 0x3b, 0x7d, 0x6d, 0xd0, 0xb3, 0x92, 0xd0, 0x38,
	0x04, 0xc8, 0xca, 0xc9, 0x23, 0xd0, 0x66, 0xb8, 0x8c, 0x49, 0x46, 0x9f, 0xd1, 0xf5, 0xdc, 0x50,
	0x2f, 0x4c, 0x48, 0xaa, 0xe0, 0x75, 0xfb, 0xb0, 0x65, 0x7e, 0x00, 0x3d, 0xe3, 0x70, 0x36, 0x0d,
	0x44, 0x4e, 0xed, 0x16, 0x74, 0xf9, 0x78, 0x1c, 0xa0, 0x90, 0x50, 0x9a, 0x15, 0x47, 0x11, 0x9a,
	0xcd, 0x43, 0x26, 0x24, 0x9a, 0x66, 0xa9, 0xc0, 0xbc, 0x83, 0x27, 0x35, 0x48, 0xc1, 0x82, 0xb3,
	0x00, 0xc9, 0x2e, 0x74, 0x03, 0x41, 0x45, 0x18, 0x48, 0xa8, 0xb5, 0xd1, 0x9a, 0x54, 0x7f, 0x21,
	0x97, 0xac, 0x38, 0x15, 0xe1, 0x0a, 0x2e, 0xa8, 0x97, 0xe0, 0xca, 0x80, 0xf4, 0x21, 0x32, 0x94,
	0xae, 0xc9, 0x5b, 0xdb, 0x90, 0xfb, 0x2e, 0xa9, 0x7b, 0xc2, 0xc4, 0x54, 0x2c, 0xad, 0x28, 0x65,
	0x5e, 0xe7, 0xdf, 0xec, 0x02, 0xa9, 0x6f, 0x4f, 0x8a, 0x2a, 0xc6, 0x53, 0x4f, 0xa0, 0x1f, 0x5f,
	0x48, 0x1c, 0xe5, 0xd4, 0xb5, 0xeb, 0xd5, 0x69, 0x79, 0x75, 0xdf, 0xe1, 0x69, 0xed, 0x19, 0xff,
	0x42, 0xdf, 0x01, 0x6c, 0xe7, 0xce, 0x0e, 0x5d, 0x17, 0x03, 0xf1, 0x5e, 0x8a, 0x48, 0x34, 0x6e,
	0x42, 0x67, 0xca, 0x16, 0xa1, 0x88, 0x25, 0xaa, 0xc0, 0xfc, 0x0a, 0x3b, 0x8d, 0xfb, 0xfe, 0x84,
	0x77, 0x76, 0x83, 0x6d, 0x69, 0xbb, 0x38, 0x32, 0x69, 0x1e, 0xdf, 0xc2, 0x85, 0x47, 0x6d, 0xfc,
	0xa8, 0x1c, 0x99, 0x10, 0x33, 0xe1, 0xc1, 0x9c, 0x0a, 0x7b, 0x82, 0xce, 0x95, 0xf4, 0x9f, 0xe2,
	0x57, 0x58, 0x23, 0x06, 0xfc, 0xcf, 0xf0, 0xf6, 0x2a, 0xe7, 0xcf, 0x34, 0x36, 0x7f, 0xb4, 0xf2,
	0xda, 0x4f, 0xee, 0x04, 0x32, 0xa7, 0x74, 0xc4, 0x2e, 0xac, 0xcc, 0x93, 0x9e, 0xdc, 0x18, 0x3d,
	0x94, 0x02, 0x54, 0xe1, 0x39, 0x77, 0xd0, 0x92, 0xc9, 0x0a, 0x0f, 0x25, 0xa4, 0x99, 0x87, 0x26,
	0xf3, 0x19, 0x8f, 0x83, 0xbc, 0xc5, 0xce, 0xd1, 0x77, 0xf1, 0x34, 0x88, 0x34, 0x2b, 0x0a, 0x3a,
	0xac, 0xda, 0x9c, 0x09, 0x64, 0xc9, 0x03, 0x24, 0xe1, 0xe8, 0x67, 0x07, 0x20, 0xdb, 0x48, 0xde,
	0x40, 0x57, 0xcd, 0x3c, 0xf2, 0xac, 0xd4, 0xfe, 0x85, 0x51, 0x68, 0x10, 0x99, 0x3d, 0xf6, 0x28,
	0x9b, 0x25, 0x4f, 0x65, 0xfe, 0x47, 0x8e, 0xa1, 0x97, 0x0e, 0x31, 0xb2, 0x53, 0x02, 0x28, 0x8f,
	0xb7, 0x66, 0x8c, 0x74, 0xd2, 0x54, 0x30, 0xca, 0x33, 0xa8, 0x01, 0xe3, 0x14, 0x56, 0xe3, 0xfe,
	0x26, 0xcf, 0x4b, 0x08, 0xc5, 0x09, 0x62, 0x6c, 0x37, 0xa5, 0x53, 0xac, 0x4f, 0xd0, 0x4b, 0xbb,
	0xa9, 0xc2, 0xa7, 0xdc, 0xcb, 0x46, 0xbf, 0xb9, 0x20, 0x45, 0xfc, 0x02, 0xeb, 0x05, 0xaf, 0x93,
	0xdd, 0xf2, 0xa6, 0x9a, 0x0e, 0x32, 0xf6, 0xee, 0x2f, 0x4a, 0xd1, 0xcf, 0x60, 0xa3, 0xe8, 0x74,
	0xb2, 0x57, 0x79, 0x88, 0x9a, 0x46, 0x68, 0xbc, 0xc9, 0xf5, 0x82, 0xa7, 0x2b, 0x5c, 0xeb, 0x1c,
	0xdf, 0xfc, 0xb2, 0xa9, 0x31, 0x2b, 0x37, 0x59, 0xb6, 0x6c, 0x3d, 0xc6, 0x75, 0x57, 0xfe, 0xa4,
	0x5f, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x85, 0x86, 0x4b, 0xf9, 0xdf, 0x07, 0x00, 0x00,
}
