// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tag/collection.proto

package tag

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 添加标签的请求
type AddTagRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flag                 int64    `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Alias                string   `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagRequest) Reset()         { *m = AddTagRequest{} }
func (m *AddTagRequest) String() string { return proto.CompactTextString(m) }
func (*AddTagRequest) ProtoMessage()    {}
func (*AddTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{0}
}

func (m *AddTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagRequest.Unmarshal(m, b)
}
func (m *AddTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagRequest.Marshal(b, m, deterministic)
}
func (m *AddTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagRequest.Merge(m, src)
}
func (m *AddTagRequest) XXX_Size() int {
	return xxx_messageInfo_AddTagRequest.Size(m)
}
func (m *AddTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagRequest proto.InternalMessageInfo

func (m *AddTagRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AddTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddTagRequest) GetFlag() int64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *AddTagRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

// 删除标签的请求
type RemoveTagRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTagRequest) Reset()         { *m = RemoveTagRequest{} }
func (m *RemoveTagRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTagRequest) ProtoMessage()    {}
func (*RemoveTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{1}
}

func (m *RemoveTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTagRequest.Unmarshal(m, b)
}
func (m *RemoveTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTagRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTagRequest.Merge(m, src)
}
func (m *RemoveTagRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTagRequest.Size(m)
}
func (m *RemoveTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTagRequest proto.InternalMessageInfo

func (m *RemoveTagRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// 更新标签的请求
type UpdateTagRequest struct {
	Code                 string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flag                 int64             `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Alias                map[string]string `protobuf:"bytes,4,rep,name=alias,proto3" json:"alias,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Keyword              []string          `protobuf:"bytes,5,rep,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateTagRequest) Reset()         { *m = UpdateTagRequest{} }
func (m *UpdateTagRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTagRequest) ProtoMessage()    {}
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{2}
}

func (m *UpdateTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTagRequest.Unmarshal(m, b)
}
func (m *UpdateTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTagRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTagRequest.Merge(m, src)
}
func (m *UpdateTagRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTagRequest.Size(m)
}
func (m *UpdateTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTagRequest proto.InternalMessageInfo

func (m *UpdateTagRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UpdateTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateTagRequest) GetFlag() int64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *UpdateTagRequest) GetAlias() map[string]string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *UpdateTagRequest) GetKeyword() []string {
	if m != nil {
		return m.Keyword
	}
	return nil
}

// 列举标签的请求
type ListTagRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTagRequest) Reset()         { *m = ListTagRequest{} }
func (m *ListTagRequest) String() string { return proto.CompactTextString(m) }
func (*ListTagRequest) ProtoMessage()    {}
func (*ListTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{3}
}

func (m *ListTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagRequest.Unmarshal(m, b)
}
func (m *ListTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagRequest.Marshal(b, m, deterministic)
}
func (m *ListTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagRequest.Merge(m, src)
}
func (m *ListTagRequest) XXX_Size() int {
	return xxx_messageInfo_ListTagRequest.Size(m)
}
func (m *ListTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagRequest proto.InternalMessageInfo

func (m *ListTagRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListTagRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 列举标签的回复
type ListTagResponse struct {
	Status               *Status      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Tag                  []*TagEntity `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListTagResponse) Reset()         { *m = ListTagResponse{} }
func (m *ListTagResponse) String() string { return proto.CompactTextString(m) }
func (*ListTagResponse) ProtoMessage()    {}
func (*ListTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{4}
}

func (m *ListTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagResponse.Unmarshal(m, b)
}
func (m *ListTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagResponse.Marshal(b, m, deterministic)
}
func (m *ListTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagResponse.Merge(m, src)
}
func (m *ListTagResponse) XXX_Size() int {
	return xxx_messageInfo_ListTagResponse.Size(m)
}
func (m *ListTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagResponse proto.InternalMessageInfo

func (m *ListTagResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListTagResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListTagResponse) GetTag() []*TagEntity {
	if m != nil {
		return m.Tag
	}
	return nil
}

// 搜索标签的请求
type SearchTagRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTagRequest) Reset()         { *m = SearchTagRequest{} }
func (m *SearchTagRequest) String() string { return proto.CompactTextString(m) }
func (*SearchTagRequest) ProtoMessage()    {}
func (*SearchTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{5}
}

func (m *SearchTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTagRequest.Unmarshal(m, b)
}
func (m *SearchTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTagRequest.Marshal(b, m, deterministic)
}
func (m *SearchTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTagRequest.Merge(m, src)
}
func (m *SearchTagRequest) XXX_Size() int {
	return xxx_messageInfo_SearchTagRequest.Size(m)
}
func (m *SearchTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTagRequest proto.InternalMessageInfo

func (m *SearchTagRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *SearchTagRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SearchTagRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 搜索标签的回复
type SearchTagResponse struct {
	Status               *Status      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Tag                  []*TagEntity `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SearchTagResponse) Reset()         { *m = SearchTagResponse{} }
func (m *SearchTagResponse) String() string { return proto.CompactTextString(m) }
func (*SearchTagResponse) ProtoMessage()    {}
func (*SearchTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{6}
}

func (m *SearchTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTagResponse.Unmarshal(m, b)
}
func (m *SearchTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTagResponse.Marshal(b, m, deterministic)
}
func (m *SearchTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTagResponse.Merge(m, src)
}
func (m *SearchTagResponse) XXX_Size() int {
	return xxx_messageInfo_SearchTagResponse.Size(m)
}
func (m *SearchTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTagResponse proto.InternalMessageInfo

func (m *SearchTagResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SearchTagResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchTagResponse) GetTag() []*TagEntity {
	if m != nil {
		return m.Tag
	}
	return nil
}

// 智能提示关键字的请求
type SuggestKeywordRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuggestKeywordRequest) Reset()         { *m = SuggestKeywordRequest{} }
func (m *SuggestKeywordRequest) String() string { return proto.CompactTextString(m) }
func (*SuggestKeywordRequest) ProtoMessage()    {}
func (*SuggestKeywordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{7}
}

func (m *SuggestKeywordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestKeywordRequest.Unmarshal(m, b)
}
func (m *SuggestKeywordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestKeywordRequest.Marshal(b, m, deterministic)
}
func (m *SuggestKeywordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestKeywordRequest.Merge(m, src)
}
func (m *SuggestKeywordRequest) XXX_Size() int {
	return xxx_messageInfo_SuggestKeywordRequest.Size(m)
}
func (m *SuggestKeywordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestKeywordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestKeywordRequest proto.InternalMessageInfo

func (m *SuggestKeywordRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

// 智能提示关键字的回复
type SuggestKeywordResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Keyword              []string `protobuf:"bytes,2,rep,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuggestKeywordResponse) Reset()         { *m = SuggestKeywordResponse{} }
func (m *SuggestKeywordResponse) String() string { return proto.CompactTextString(m) }
func (*SuggestKeywordResponse) ProtoMessage()    {}
func (*SuggestKeywordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{8}
}

func (m *SuggestKeywordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestKeywordResponse.Unmarshal(m, b)
}
func (m *SuggestKeywordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestKeywordResponse.Marshal(b, m, deterministic)
}
func (m *SuggestKeywordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestKeywordResponse.Merge(m, src)
}
func (m *SuggestKeywordResponse) XXX_Size() int {
	return xxx_messageInfo_SuggestKeywordResponse.Size(m)
}
func (m *SuggestKeywordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestKeywordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestKeywordResponse proto.InternalMessageInfo

func (m *SuggestKeywordResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SuggestKeywordResponse) GetKeyword() []string {
	if m != nil {
		return m.Keyword
	}
	return nil
}

// 替换关键字的请求
type ReplaceKeywordRequest struct {
	MatchedValue         string   `protobuf:"bytes,1,opt,name=matchedValue,proto3" json:"matchedValue,omitempty"`
	NewValue             string   `protobuf:"bytes,2,opt,name=newValue,proto3" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceKeywordRequest) Reset()         { *m = ReplaceKeywordRequest{} }
func (m *ReplaceKeywordRequest) String() string { return proto.CompactTextString(m) }
func (*ReplaceKeywordRequest) ProtoMessage()    {}
func (*ReplaceKeywordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{9}
}

func (m *ReplaceKeywordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceKeywordRequest.Unmarshal(m, b)
}
func (m *ReplaceKeywordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceKeywordRequest.Marshal(b, m, deterministic)
}
func (m *ReplaceKeywordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceKeywordRequest.Merge(m, src)
}
func (m *ReplaceKeywordRequest) XXX_Size() int {
	return xxx_messageInfo_ReplaceKeywordRequest.Size(m)
}
func (m *ReplaceKeywordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceKeywordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceKeywordRequest proto.InternalMessageInfo

func (m *ReplaceKeywordRequest) GetMatchedValue() string {
	if m != nil {
		return m.MatchedValue
	}
	return ""
}

func (m *ReplaceKeywordRequest) GetNewValue() string {
	if m != nil {
		return m.NewValue
	}
	return ""
}

// 扩展关键字的请求
type ExtendKeywordRequest struct {
	Mode                 ExtendMode `protobuf:"varint,1,opt,name=mode,proto3,enum=tag.ExtendMode" json:"mode,omitempty"`
	MatchedValue         []string   `protobuf:"bytes,2,rep,name=matchedValue,proto3" json:"matchedValue,omitempty"`
	NewValue             []string   `protobuf:"bytes,3,rep,name=newValue,proto3" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ExtendKeywordRequest) Reset()         { *m = ExtendKeywordRequest{} }
func (m *ExtendKeywordRequest) String() string { return proto.CompactTextString(m) }
func (*ExtendKeywordRequest) ProtoMessage()    {}
func (*ExtendKeywordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{10}
}

func (m *ExtendKeywordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtendKeywordRequest.Unmarshal(m, b)
}
func (m *ExtendKeywordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtendKeywordRequest.Marshal(b, m, deterministic)
}
func (m *ExtendKeywordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtendKeywordRequest.Merge(m, src)
}
func (m *ExtendKeywordRequest) XXX_Size() int {
	return xxx_messageInfo_ExtendKeywordRequest.Size(m)
}
func (m *ExtendKeywordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtendKeywordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtendKeywordRequest proto.InternalMessageInfo

func (m *ExtendKeywordRequest) GetMode() ExtendMode {
	if m != nil {
		return m.Mode
	}
	return ExtendMode_INVALID
}

func (m *ExtendKeywordRequest) GetMatchedValue() []string {
	if m != nil {
		return m.MatchedValue
	}
	return nil
}

func (m *ExtendKeywordRequest) GetNewValue() []string {
	if m != nil {
		return m.NewValue
	}
	return nil
}

// 合并Json格式数据的请求
type MergeJsonRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeJsonRequest) Reset()         { *m = MergeJsonRequest{} }
func (m *MergeJsonRequest) String() string { return proto.CompactTextString(m) }
func (*MergeJsonRequest) ProtoMessage()    {}
func (*MergeJsonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a89965900be93e, []int{11}
}

func (m *MergeJsonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeJsonRequest.Unmarshal(m, b)
}
func (m *MergeJsonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeJsonRequest.Marshal(b, m, deterministic)
}
func (m *MergeJsonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeJsonRequest.Merge(m, src)
}
func (m *MergeJsonRequest) XXX_Size() int {
	return xxx_messageInfo_MergeJsonRequest.Size(m)
}
func (m *MergeJsonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeJsonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MergeJsonRequest proto.InternalMessageInfo

func (m *MergeJsonRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*AddTagRequest)(nil), "tag.AddTagRequest")
	proto.RegisterType((*RemoveTagRequest)(nil), "tag.RemoveTagRequest")
	proto.RegisterType((*UpdateTagRequest)(nil), "tag.UpdateTagRequest")
	proto.RegisterMapType((map[string]string)(nil), "tag.UpdateTagRequest.AliasEntry")
	proto.RegisterType((*ListTagRequest)(nil), "tag.ListTagRequest")
	proto.RegisterType((*ListTagResponse)(nil), "tag.ListTagResponse")
	proto.RegisterType((*SearchTagRequest)(nil), "tag.SearchTagRequest")
	proto.RegisterType((*SearchTagResponse)(nil), "tag.SearchTagResponse")
	proto.RegisterType((*SuggestKeywordRequest)(nil), "tag.SuggestKeywordRequest")
	proto.RegisterType((*SuggestKeywordResponse)(nil), "tag.SuggestKeywordResponse")
	proto.RegisterType((*ReplaceKeywordRequest)(nil), "tag.ReplaceKeywordRequest")
	proto.RegisterType((*ExtendKeywordRequest)(nil), "tag.ExtendKeywordRequest")
	proto.RegisterType((*MergeJsonRequest)(nil), "tag.MergeJsonRequest")
}

func init() {
	proto.RegisterFile("proto/tag/collection.proto", fileDescriptor_b2a89965900be93e)
}

var fileDescriptor_b2a89965900be93e = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x26, 0x71, 0x9a, 0x92, 0x29, 0x4d, 0xc3, 0xd2, 0x46, 0xc6, 0x5c, 0x22, 0x57, 0x42, 0x39,
	0xa0, 0x54, 0x04, 0xa9, 0x8a, 0x10, 0x42, 0xb4, 0x28, 0x17, 0x4a, 0x2f, 0x4e, 0x69, 0x25, 0x6e,
	0x8b, 0x3d, 0x71, 0xa2, 0x38, 0xbb, 0xc1, 0x9e, 0xb4, 0x44, 0x3c, 0x18, 0xef, 0xc2, 0xd3, 0x20,
	0xef, 0xda, 0x8e, 0x6d, 0x12, 0x7e, 0x24, 0xc4, 0xcd, 0xf3, 0xf7, 0xcd, 0x37, 0x93, 0x6f, 0x27,
	0x60, 0x2d, 0x42, 0x49, 0xf2, 0x84, 0xb8, 0x7f, 0xe2, 0xca, 0x20, 0x40, 0x97, 0xa6, 0x52, 0xf4,
	0x94, 0x93, 0x19, 0xc4, 0x7d, 0xab, 0xbd, 0x4e, 0x88, 0x26, 0x3c, 0x44, 0x4f, 0x07, 0x6d, 0x0e,
	0xfb, 0x67, 0x9e, 0x77, 0xc5, 0x7d, 0x07, 0x3f, 0x2f, 0x31, 0x22, 0xc6, 0xa0, 0xe6, 0x4a, 0x0f,
	0xcd, 0x4a, 0xa7, 0xd2, 0x6d, 0x38, 0xea, 0x3b, 0xf6, 0x09, 0x3e, 0x47, 0xb3, 0xaa, 0x7d, 0xf1,
	0x77, 0xec, 0x1b, 0x07, 0xdc, 0x37, 0x8d, 0x4e, 0xa5, 0x6b, 0x38, 0xea, 0x9b, 0x1d, 0xc2, 0x0e,
	0x0f, 0xa6, 0x3c, 0x32, 0x6b, 0x2a, 0x51, 0x1b, 0xf6, 0x53, 0x68, 0x39, 0x38, 0x97, 0xb7, 0xf8,
	0xeb, 0x2e, 0xf6, 0xf7, 0x0a, 0xb4, 0x3e, 0x2c, 0x3c, 0x4e, 0xf8, 0x8f, 0xe8, 0x9c, 0xae, 0xe9,
	0x18, 0xdd, 0xbd, 0x7e, 0xa7, 0x47, 0xdc, 0xef, 0x95, 0x3b, 0xf4, 0xce, 0xe2, 0x94, 0xa1, 0xa0,
	0x70, 0x95, 0x10, 0x66, 0x26, 0xec, 0xce, 0x70, 0x75, 0x27, 0x43, 0xcf, 0xdc, 0xe9, 0x18, 0xdd,
	0x86, 0x93, 0x9a, 0xd6, 0x00, 0x60, 0x9d, 0xce, 0x5a, 0x60, 0xcc, 0x70, 0x95, 0x50, 0x8b, 0x3f,
	0xe3, 0x05, 0xdc, 0xf2, 0x60, 0x99, 0x52, 0xd3, 0xc6, 0xcb, 0xea, 0xa0, 0x62, 0xbf, 0x86, 0xe6,
	0xfb, 0x69, 0x44, 0xb9, 0xc9, 0xda, 0x50, 0x97, 0xe3, 0x71, 0x84, 0xa4, 0x00, 0x0c, 0x27, 0xb1,
	0x62, 0x0c, 0x57, 0x2e, 0x05, 0x29, 0x0c, 0xc3, 0xd1, 0x86, 0x2d, 0xe0, 0x20, 0xab, 0x8f, 0x16,
	0x52, 0x44, 0xc8, 0x8e, 0xa1, 0x1e, 0x11, 0xa7, 0x65, 0xa4, 0x00, 0xf6, 0xfa, 0x7b, 0x6a, 0xbe,
	0x91, 0x72, 0x39, 0x49, 0x28, 0x46, 0x23, 0x49, 0x3c, 0x48, 0xd1, 0x94, 0xc1, 0x3a, 0x10, 0x8b,
	0xc2, 0x34, 0xd4, 0x5e, 0x9a, 0xaa, 0xee, 0x8a, 0xfb, 0x43, 0x41, 0x53, 0x5a, 0x39, 0x71, 0xc8,
	0xfe, 0x08, 0xad, 0x11, 0xf2, 0xd0, 0x9d, 0xe4, 0x18, 0xe7, 0xf6, 0xa2, 0x67, 0x4e, 0xcd, 0xdc,
	0x2c, 0xd5, 0xcd, 0xb3, 0x18, 0xf9, 0x59, 0x16, 0xf0, 0x30, 0x87, 0xfd, 0x3f, 0xa6, 0x79, 0x0e,
	0x47, 0xa3, 0xa5, 0xef, 0x63, 0x44, 0x17, 0x9a, 0xf1, 0x6f, 0x47, 0xb2, 0x6f, 0xa0, 0x5d, 0x2e,
	0xf9, 0x1b, 0xa6, 0x39, 0xe0, 0x6a, 0x41, 0x43, 0xf6, 0x0d, 0x1c, 0x39, 0xb8, 0x08, 0xb8, 0x8b,
	0x25, 0x2e, 0x36, 0x3c, 0x98, 0x73, 0x72, 0x27, 0xe8, 0x5d, 0x2b, 0x0d, 0x69, 0x42, 0x05, 0x1f,
	0xb3, 0xe0, 0xbe, 0xc0, 0xbb, 0xeb, 0x9c, 0xc6, 0x32, 0xdb, 0xfe, 0x0a, 0x87, 0xc3, 0x2f, 0x84,
	0xc2, 0x2b, 0xe1, 0x1e, 0x43, 0x6d, 0x9e, 0x3e, 0xa1, 0x66, 0xff, 0x40, 0xb1, 0xd5, 0x89, 0x97,
	0xd2, 0x43, 0x47, 0x05, 0x7f, 0x6a, 0xae, 0x49, 0x6f, 0x6f, 0x6e, 0xa8, 0xf8, 0xba, 0xf9, 0x33,
	0x68, 0x5d, 0x62, 0xe8, 0xe3, 0xbb, 0x48, 0x8a, 0xdc, 0x72, 0x5d, 0x29, 0x08, 0x05, 0xa5, 0xcb,
	0x4d, 0xcc, 0xfe, 0xb7, 0x1a, 0xc0, 0xdb, 0xec, 0x4e, 0xb1, 0x3e, 0xd4, 0xf5, 0x11, 0x62, 0x4c,
	0xb1, 0x2b, 0x5c, 0x24, 0x4b, 0xfb, 0xce, 0x03, 0x2e, 0x66, 0xe9, 0x6f, 0x60, 0xdf, 0x63, 0x03,
	0x68, 0x64, 0x57, 0x85, 0x1d, 0xa9, 0x94, 0xf2, 0x95, 0xd9, 0x5e, 0x99, 0x1d, 0x81, 0xa4, 0xb2,
	0x7c, 0x14, 0xb6, 0x54, 0x9e, 0xc2, 0x6e, 0xf2, 0x08, 0xd9, 0x23, 0x95, 0x50, 0x7c, 0xd2, 0xd6,
	0x61, 0xd1, 0x99, 0xd5, 0xbd, 0x82, 0x46, 0x26, 0xf8, 0xa4, 0x63, 0xf9, 0x71, 0x59, 0xed, 0xb2,
	0x3b, 0xab, 0xbe, 0x80, 0x66, 0x51, 0x89, 0xcc, 0xd2, 0xb9, 0x9b, 0x14, 0x6d, 0x3d, 0xd9, 0x18,
	0xcb, 0xc0, 0xce, 0xa1, 0x59, 0x54, 0x5f, 0x02, 0xb6, 0x51, 0x92, 0x5b, 0xd6, 0xf0, 0x06, 0xf6,
	0x0b, 0x42, 0x63, 0x8f, 0x73, 0x9a, 0xfa, 0x23, 0x84, 0x01, 0x34, 0x32, 0xb5, 0x24, 0x0b, 0x29,
	0xab, 0x67, 0x73, 0xe5, 0xa7, 0xba, 0xfa, 0xdb, 0x7a, 0xf1, 0x23, 0x00, 0x00, 0xff, 0xff, 0x52,
	0x75, 0xe0, 0x81, 0xf1, 0x06, 0x00, 0x00,
}
