// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tag/dummy.proto

package tag

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 添加标签的请求
type AddTagRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagRequest) Reset()         { *m = AddTagRequest{} }
func (m *AddTagRequest) String() string { return proto.CompactTextString(m) }
func (*AddTagRequest) ProtoMessage()    {}
func (*AddTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab4a3ff9059ec40, []int{0}
}

func (m *AddTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagRequest.Unmarshal(m, b)
}
func (m *AddTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagRequest.Marshal(b, m, deterministic)
}
func (m *AddTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagRequest.Merge(m, src)
}
func (m *AddTagRequest) XXX_Size() int {
	return xxx_messageInfo_AddTagRequest.Size(m)
}
func (m *AddTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagRequest proto.InternalMessageInfo

func (m *AddTagRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AddTagRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

// 删除标签的请求
type RemoveTagRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTagRequest) Reset()         { *m = RemoveTagRequest{} }
func (m *RemoveTagRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTagRequest) ProtoMessage()    {}
func (*RemoveTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab4a3ff9059ec40, []int{1}
}

func (m *RemoveTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTagRequest.Unmarshal(m, b)
}
func (m *RemoveTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTagRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTagRequest.Merge(m, src)
}
func (m *RemoveTagRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTagRequest.Size(m)
}
func (m *RemoveTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTagRequest proto.InternalMessageInfo

func (m *RemoveTagRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RemoveTagRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

// 检索标签的请求
type FilterTagRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Code                 []string `protobuf:"bytes,3,rep,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterTagRequest) Reset()         { *m = FilterTagRequest{} }
func (m *FilterTagRequest) String() string { return proto.CompactTextString(m) }
func (*FilterTagRequest) ProtoMessage()    {}
func (*FilterTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab4a3ff9059ec40, []int{2}
}

func (m *FilterTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterTagRequest.Unmarshal(m, b)
}
func (m *FilterTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterTagRequest.Marshal(b, m, deterministic)
}
func (m *FilterTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterTagRequest.Merge(m, src)
}
func (m *FilterTagRequest) XXX_Size() int {
	return xxx_messageInfo_FilterTagRequest.Size(m)
}
func (m *FilterTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterTagRequest proto.InternalMessageInfo

func (m *FilterTagRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FilterTagRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *FilterTagRequest) GetCode() []string {
	if m != nil {
		return m.Code
	}
	return nil
}

// 检索标签的回复
type FilterTagResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Owner                []string `protobuf:"bytes,3,rep,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterTagResponse) Reset()         { *m = FilterTagResponse{} }
func (m *FilterTagResponse) String() string { return proto.CompactTextString(m) }
func (*FilterTagResponse) ProtoMessage()    {}
func (*FilterTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab4a3ff9059ec40, []int{3}
}

func (m *FilterTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterTagResponse.Unmarshal(m, b)
}
func (m *FilterTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterTagResponse.Marshal(b, m, deterministic)
}
func (m *FilterTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterTagResponse.Merge(m, src)
}
func (m *FilterTagResponse) XXX_Size() int {
	return xxx_messageInfo_FilterTagResponse.Size(m)
}
func (m *FilterTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterTagResponse proto.InternalMessageInfo

func (m *FilterTagResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *FilterTagResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *FilterTagResponse) GetOwner() []string {
	if m != nil {
		return m.Owner
	}
	return nil
}

func init() {
	proto.RegisterType((*AddTagRequest)(nil), "tag.AddTagRequest")
	proto.RegisterType((*RemoveTagRequest)(nil), "tag.RemoveTagRequest")
	proto.RegisterType((*FilterTagRequest)(nil), "tag.FilterTagRequest")
	proto.RegisterType((*FilterTagResponse)(nil), "tag.FilterTagResponse")
}

func init() {
	proto.RegisterFile("proto/tag/dummy.proto", fileDescriptor_0ab4a3ff9059ec40)
}

var fileDescriptor_0ab4a3ff9059ec40 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x7c, 0x79, 0xa1, 0x91, 0xb2, 0x15, 0x52, 0xb1, 0x68, 0x54, 0xe5, 0x54, 0x85, 0x0b, 0xa7,
	0x54, 0x0a, 0x17, 0x90, 0x7a, 0x01, 0x21, 0x3e, 0xc0, 0xf4, 0x07, 0x4c, 0xbd, 0x0d, 0x88, 0x24,
	0x2e, 0xf1, 0x06, 0xc4, 0x77, 0xf1, 0x83, 0x28, 0xeb, 0x24, 0x2d, 0x91, 0xb8, 0x70, 0xf3, 0xcc,
	0x7a, 0x66, 0xd6, 0x63, 0x98, 0xef, 0x6b, 0x43, 0x66, 0x45, 0x2a, 0x5f, 0xe9, 0xa6, 0x2c, 0x3f,
	0x53, 0xc6, 0xc2, 0x27, 0x95, 0xc7, 0xd1, 0x61, 0x66, 0x9f, 0x55, 0x8d, 0xda, 0x0d, 0x93, 0x1b,
	0x38, 0xbd, 0xd5, 0x7a, 0xa3, 0x72, 0x89, 0x6f, 0x0d, 0x5a, 0x12, 0x02, 0x4e, 0xb6, 0x46, 0xe3,
	0xc2, 0x5b, 0x7a, 0x97, 0xa1, 0xe4, 0xb3, 0x38, 0x87, 0x89, 0xf9, 0xa8, 0xb0, 0x5e, 0xfc, 0x67,
	0xd2, 0x81, 0x64, 0x0d, 0x33, 0x89, 0xa5, 0x79, 0xc7, 0x3f, 0xa9, 0x37, 0x30, 0x7b, 0x78, 0x29,
	0x08, 0xeb, 0x23, 0x75, 0x04, 0x81, 0xd9, 0xed, 0x2c, 0x12, 0xeb, 0x7d, 0xd9, 0xa1, 0xd6, 0x61,
	0x6b, 0x9a, 0x8a, 0xd8, 0xc1, 0x97, 0x0e, 0x0c, 0x59, 0xfe, 0xd2, 0xef, 0xb3, 0x12, 0x0d, 0x67,
	0x47, 0xae, 0x76, 0x6f, 0x2a, 0x8b, 0xe2, 0x02, 0x02, 0x4b, 0x8a, 0x1a, 0xcb, 0xb6, 0xd3, 0x6c,
	0x9a, 0x92, 0xca, 0xd3, 0x47, 0xa6, 0x64, 0x37, 0x6a, 0x33, 0xc8, 0x90, 0x2a, 0xfa, 0x0c, 0x06,
	0x87, 0xdd, 0x5d, 0x88, 0x03, 0xd9, 0x97, 0x07, 0x93, 0xfb, 0xb6, 0x61, 0x91, 0x41, 0xe0, 0xea,
	0x13, 0x82, 0x4d, 0x7f, 0x74, 0x19, 0x3b, 0xee, 0xae, 0x50, 0xd5, 0x6b, 0xbf, 0x4c, 0xf2, 0x4f,
	0x5c, 0x43, 0x38, 0xf4, 0x26, 0xe6, 0x7c, 0x65, 0xdc, 0xe3, 0x2f, 0xca, 0x35, 0x84, 0xc3, 0xeb,
	0x3a, 0xe5, 0xb8, 0xc3, 0x38, 0x1a, 0xd3, 0xbd, 0xfa, 0x29, 0xe0, 0x1f, 0xbf, 0xfa, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0xeb, 0xc8, 0x5e, 0x27, 0x02, 0x00, 0x00,
}
