// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tag/shared.proto

package tag

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExtendMode int32

const (
	ExtendMode_INVALID ExtendMode = 0
	ExtendMode_AND     ExtendMode = 1
	ExtendMode_OR      ExtendMode = 2
)

var ExtendMode_name = map[int32]string{
	0: "INVALID",
	1: "AND",
	2: "OR",
}

var ExtendMode_value = map[string]int32{
	"INVALID": 0,
	"AND":     1,
	"OR":      2,
}

func (x ExtendMode) String() string {
	return proto.EnumName(ExtendMode_name, int32(x))
}

func (ExtendMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bad5ac56f59de91b, []int{0}
}

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_bad5ac56f59de91b, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 空白回复
type BlankResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankResponse) Reset()         { *m = BlankResponse{} }
func (m *BlankResponse) String() string { return proto.CompactTextString(m) }
func (*BlankResponse) ProtoMessage()    {}
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bad5ac56f59de91b, []int{1}
}

func (m *BlankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankResponse.Unmarshal(m, b)
}
func (m *BlankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankResponse.Marshal(b, m, deterministic)
}
func (m *BlankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankResponse.Merge(m, src)
}
func (m *BlankResponse) XXX_Size() int {
	return xxx_messageInfo_BlankResponse.Size(m)
}
func (m *BlankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlankResponse proto.InternalMessageInfo

func (m *BlankResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// 标签实体
type TagEntity struct {
	Code                 string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flag                 int64             `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Alias                map[string]string `protobuf:"bytes,4,rep,name=alias,proto3" json:"alias,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Keyword              []string          `protobuf:"bytes,5,rep,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TagEntity) Reset()         { *m = TagEntity{} }
func (m *TagEntity) String() string { return proto.CompactTextString(m) }
func (*TagEntity) ProtoMessage()    {}
func (*TagEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_bad5ac56f59de91b, []int{2}
}

func (m *TagEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagEntity.Unmarshal(m, b)
}
func (m *TagEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagEntity.Marshal(b, m, deterministic)
}
func (m *TagEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagEntity.Merge(m, src)
}
func (m *TagEntity) XXX_Size() int {
	return xxx_messageInfo_TagEntity.Size(m)
}
func (m *TagEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_TagEntity.DiscardUnknown(m)
}

var xxx_messageInfo_TagEntity proto.InternalMessageInfo

func (m *TagEntity) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TagEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TagEntity) GetFlag() int64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *TagEntity) GetAlias() map[string]string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *TagEntity) GetKeyword() []string {
	if m != nil {
		return m.Keyword
	}
	return nil
}

func init() {
	proto.RegisterEnum("tag.ExtendMode", ExtendMode_name, ExtendMode_value)
	proto.RegisterType((*Status)(nil), "tag.Status")
	proto.RegisterType((*BlankResponse)(nil), "tag.BlankResponse")
	proto.RegisterType((*TagEntity)(nil), "tag.TagEntity")
	proto.RegisterMapType((map[string]string)(nil), "tag.TagEntity.AliasEntry")
}

func init() {
	proto.RegisterFile("proto/tag/shared.proto", fileDescriptor_bad5ac56f59de91b)
}

var fileDescriptor_bad5ac56f59de91b = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0x36, 0xcd, 0xda, 0xb1, 0x57, 0x84, 0x12, 0x44, 0xa2, 0xa7, 0x32, 0x2f, 0x65, 0x87, 0x0e,
	0xa6, 0xc8, 0xf0, 0x36, 0xd9, 0x0e, 0x03, 0x9d, 0x10, 0xc5, 0xfb, 0xd3, 0xc6, 0x38, 0xd6, 0xa5,
	0xa3, 0xc9, 0xd4, 0xfe, 0x8f, 0xfe, 0x51, 0x92, 0xac, 0x55, 0xbc, 0x7d, 0xdf, 0x7b, 0x8f, 0xef,
	0xc7, 0x83, 0xd3, 0x5d, 0x5d, 0xd9, 0x6a, 0x6c, 0x51, 0x8d, 0xcd, 0x3b, 0xd6, 0xb2, 0xc8, 0xfd,
	0x80, 0x51, 0x8b, 0x6a, 0x78, 0x0d, 0xd1, 0xa3, 0x45, 0xbb, 0x37, 0x8c, 0x41, 0xef, 0xb5, 0x2a,
	0x24, 0x27, 0x29, 0xc9, 0x42, 0xe1, 0x31, 0xe3, 0xd0, 0xdf, 0x4a, 0x63, 0x50, 0x49, 0x1e, 0xa4,
	0x24, 0x1b, 0x88, 0x8e, 0x0e, 0xaf, 0xe0, 0xf8, 0xb6, 0x44, 0xbd, 0x11, 0xd2, 0xec, 0x2a, 0x6d,
	0x24, 0xbb, 0x80, 0xc8, 0x78, 0x21, 0x2f, 0x10, 0x4f, 0xe2, 0xdc, 0xa2, 0xca, 0x0f, 0xda, 0xa2,
	0x5d, 0x0d, 0xbf, 0x09, 0x0c, 0x9e, 0x50, 0x2d, 0xb4, 0x5d, 0xdb, 0xe6, 0x9f, 0xe3, 0xa0, 0x75,
	0x64, 0xd0, 0xd3, 0xb8, 0xed, 0xec, 0x3c, 0x76, 0xb3, 0xb7, 0x12, 0x15, 0xa7, 0x29, 0xc9, 0xa8,
	0xf0, 0x98, 0x8d, 0x21, 0xc4, 0x72, 0x8d, 0x86, 0xf7, 0x52, 0x9a, 0xc5, 0x93, 0x33, 0xef, 0xf6,
	0x2b, 0x9d, 0xcf, 0xdc, 0x6e, 0xa1, 0x6d, 0xdd, 0x88, 0xc3, 0x9d, 0xab, 0xb2, 0x91, 0xcd, 0x67,
	0x55, 0x17, 0x3c, 0x4c, 0xa9, 0xab, 0xd2, 0xd2, 0xf3, 0x29, 0xc0, 0xdf, 0x39, 0x4b, 0x80, 0x6e,
	0x64, 0xd3, 0x66, 0x72, 0x90, 0x9d, 0x40, 0xf8, 0x81, 0xe5, 0xbe, 0xcb, 0x74, 0x20, 0x37, 0xc1,
	0x94, 0x8c, 0x46, 0x00, 0x8b, 0x2f, 0x2b, 0x75, 0x71, 0xef, 0xa2, 0xc7, 0xd0, 0x5f, 0xae, 0x9e,
	0x67, 0x77, 0xcb, 0x79, 0x72, 0xc4, 0xfa, 0x40, 0x67, 0xab, 0x79, 0x42, 0x58, 0x04, 0xc1, 0x83,
	0x48, 0x82, 0x97, 0xc8, 0x3f, 0xfd, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xeb, 0x5d, 0x56,
	0x8e, 0x01, 0x00, 0x00,
}
